# Generated by Django 2.0.5 on 2018-05-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('hgander', models.BooleanField()),
                ('hcontent', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='bcommet',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='bread',
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='hBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booktest.BookInfo'),
        ),
    ]
