# Generated by Django 2.1 on 2018-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=20)),
                ('fdate', models.DateTimeField()),
                ('fcontact', models.CharField(max_length=22)),
                ('fcontent', models.CharField(max_length=400)),
            ],
        ),
    ]
